[package]
name = "nft_examples"

[dependencies]
Mgo = { git = "https://github.com/MangoNetworkOs/Mango.git", subdir = "crates/mgo-framework/packages/mgo-framework", rev = "framework/testnet" }

[addresses]
nft_examples = "0x0"
